Vagrant.configure("2") do |config|
  config.vm.box = "puphpet/centos7-x64"
  config.ssh.forward_agent = true
  config.vm.network "private_network", ip: "192.168.33.50"
  config.vm.synced_folder "../shared", "/var/www", create: true
  config.vm.synced_folder "../ansible", "/ansible"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

#  config.vm.define "web", primary: true do |web|
#    web.vm.network :private_network, ip: "192.168.33.50"
#    web.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
#    web.vm.network :forwarded_port, guest: 443, host: 8081, auto_correct: true
#    web.vm.hostname = "ansibleMpwar"
#  end

end
